### ISSUE TITLE
rn-sumup looks like out dated

### ISSUE THREAD

**Issue by shadmaan-nexilis** [ReactNativeBrasil/react-native-sum-up#10]

**Comment by shadmaan-nexilis** [comment]
Sumup sdk is updated to 3.2.2 and he has updated some import statements. can you please update the rn-sumup acordingly

**Comment by shadmaan-nexilis** [comment]
No

**Comment by ital0** [comment]
@shadmaan-nexilis I no longer do updates in this package, but if you want you could send a PR.
