### ISSUE TITLE
Could not find com.sumup:merchant-sdk:3.2.0

### ISSUE THREAD

**Issue by jameslevine** [ReactNativeBrasil/react-native-sum-up#8]
I am getting an error saying could not find com.sumup:merchant-sdk:3.2.0 after npm installing and linking the package.

Could someone help me with figuring this out? I'm just creating an android app and want to link the sumup card reader.

**Comment by ital0** [comment]
@jameslevine have you added sumup maven repository in your **android/build.gradle**?
If not, please add this line at **allProjects** entry: 

> maven { url 'https://maven.sumup.com/releases' }
